<a href="https://colab.research.google.com/github/divyap09/AI-ML/blob/main/PyTorch/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch basics

- developed by Meta (Facebook)
- popular deep learning framework
- able to access many pre built-in models

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [88]:
import torch

In [89]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [90]:
if device == 'cuda':
  !nvidia-smi


printing PyTorch version

In [91]:
#output: PyTorch version + CUDA version

torch.__version__

'2.4.0+cu121'

```
torch.tensor(type)
```

To create a tensor with pre-defined data.
It contains elements of a single data type.

1. Scalar: n-dim = 0 and denoted by lower case
2. vector: n-dim = 1 and denoted by lower case
3. matirx: n-dim = 2 and denoted by upper case
4. tensor: n-dim = non-zero and denoted by upper case

requires_grad
dtype: torch.int32 is default
device: CPU is default, cuda:0 (no. of gpus)

defining a scalar

In [92]:
scalar = torch.tensor(4)

scalar, scalar.ndim, scalar.item()

(tensor(4), 0, 4)

defining a vector

In [93]:
vector = torch.tensor([1,2,3])

vector, vector.ndim

(tensor([1, 2, 3]), 1)

In [94]:
MATRIX = torch.tensor([
                        [1,2,-3], [4,-5,6]
                      ])

MATRIX, MATRIX.ndim, MATRIX[0]

(tensor([[ 1,  2, -3],
         [ 4, -5,  6]]),
 2,
 tensor([ 1,  2, -3]))

In [95]:
TENSOR = torch.tensor([
                        [
                            [1,2,3],
                            [4,5,6],
                            [7,8,9],
                            [10,11,12]
                        ]
                      ])

TENSOR, TENSOR.ndim, TENSOR[0][1]

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]),
 3,
 tensor([4, 5, 6]))

to get a value of tensor containing single value; it converts a tensor into a scalar. If n > 1, it is unable to convert into scalar.

In [96]:
print(scalar.item())

vector_one = torch.tensor([100])
print(vector_one.item())

MATRIX_one = torch.tensor([[7]], dtype=torch.float32)
print(MATRIX_one.item())

4
100
7.0


transpose of a tensor.

```
variable.T
```

- scalars won't have this feature

In [97]:
vector.T, MATRIX.T, TENSOR.T

(tensor([1, 2, 3]),
 tensor([[ 1,  4],
         [ 2, -5],
         [-3,  6]]),
 tensor([[[ 1],
          [ 4],
          [ 7],
          [10]],
 
         [[ 2],
          [ 5],
          [ 8],
          [11]],
 
         [[ 3],
          [ 6],
          [ 9],
          [12]]]))

```
variable.shape
```
- gives the m x n x p x .. shape

In [98]:
print(vector.shape, vector.T.shape)
print(MATRIX.shape, MATRIX.T.shape)
print(TENSOR.shape, TENSOR.T.shape)

torch.Size([3]) torch.Size([3])
torch.Size([2, 3]) torch.Size([3, 2])
torch.Size([1, 4, 3]) torch.Size([3, 4, 1])


get absolute values of the tensor
abs() and absolute() are equivalent

In [99]:
print(MATRIX)
print(MATRIX.abs())
print(MATRIX.absolute())

tensor([[ 1,  2, -3],
        [ 4, -5,  6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


min and max values

In [100]:
vector.min().item(), vector.max().item()

(1, 3)

sort

In [101]:
vector.argsort(), vector

(tensor([0, 1, 2]), tensor([1, 2, 3]))

In [102]:
vector_in = torch.rand(3, dtype=torch.float32)*10
vector_out = torch.rand(3) #define the same shape as the input

#out is optional
vector_in, torch.ceil(vector_in, out=vector_out), torch.floor(vector_in)

(tensor([7.8259, 8.8875, 4.1654]), tensor([8., 9., 5.]), tensor([7., 8., 4.]))

In [103]:
vector_out

tensor([8., 9., 5.])

extract fractional part

In [127]:
torch.frac(vector_in)

tensor([0.8259, 0.8875, 0.1654])

rand() will always give decimal part between 0 and 1

In [119]:
vector_rand = torch.rand(3)
vector_rand = torch.tensor(torch.floor(vector_rand *5),dtype = torch.int)
vector_rand

<ipython-input-119-a7b8cf2132f4>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  vector_rand = torch.tensor(torch.floor(vector_rand *5),dtype = torch.int)


tensor([3, 0, 4], dtype=torch.int32)

To compare each tensor's entry with another tensor's entry

In [120]:
vector.eq(vector_rand)

tensor([False, False, False])

To compare two tensors whether they are exactly same or not

In [121]:
print(vector.equal(vector_rand))
print(vector.equal(torch.tensor([-1,2,3]).abs()))

False
True


to find the value of the exponential power,
$y = e^x$

In [124]:
vector, vector.exp()

(tensor([1, 2, 3]), tensor([ 2.7183,  7.3891, 20.0855]))